# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  webapplicationseconddockertest:
    image: webapplicationseconddockertest
    build:
      context: .
      dockerfile: WebApplication-Second-Docker-Test/Dockerfile
    ports:
      - 8080:8080
